services:
  discord-bot:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - OPENAI=${OPENAI}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    volumes:
      - .:/app
    restart: always